### ISSUE TITLE
注册账号提示“未知错误，请重试“？

### ISSUE THREAD

**Issue by yasz** [seymoe/QuillCMS#4]
注册账号时提示，另外默认管理员账号密码是？

**Comment by seymoe** [comment]
@yasz 抱歉现才回复你，目前这个repo没有在维护，由于没有文档所以肯定有诸多疑惑之处，如果想运行起来或者二次开发只能去看代码的具体实现，在这里我大概介绍一下项目的整体架构，对你的疑惑可能有帮助：

1. 本项目为nuxt+express构建，所以对vue、nuxt等这些应该要比较熟悉；
2. 本项目前后分离，但是代码在一个repo中，前后通过接口交互；
3. 前端页面在`pages`中，路由对应文件路径，前端页面分用户端和管理端，管理端入口文件夹为`/pages/quill_cms_admin`；后端等相关代码在`server`文件夹中;
4. api分为client和server，具体api对应的controller和涉及到的model文件可以去浏览；
5. 没有提供初始的用户表等数据，需要自己创造role为super的超级管理员用户。
