### ISSUE TITLE
怎么没有基础数据呢?

### ISSUE THREAD

**Issue by blackmady** [seymoe/QuillCMS#5]
没有基础数据很难跑起来啊.

**Comment by govue** [comment]
需要手动添加一个管理员进去，这样就可以进后台了，mongoDB添加数据是可以不需要建“表”而用代码添加的，我用的方法是在login提交请求api数据时，在登录controller处添加管理员到数据库(server/controllers/user.js下的loginAction())，代码：
const obj = {
      username: 'name',
      nickname: 'nikname',
      email: 'qubo@qq.com',
      password: '88888888',
      role: 'admin',
      enable: true
    }

    try {
      // 利用bcrypt对密码进行加密
      let hash = await bcrypt.hash(obj.password, saltRounds)

      if (hash) {
        obj.password = hash
        const newUser = new User(obj)
        let userObj = await newUser.save()
        return res.send(renderApiData(req, res, 200, '用户创建成功', { id: userObj._id }))
      } else {
        return res.status(500).send(renderApiErr(req, res, 500, '加密过程出错'))
      }
    } catch (err) {
      return res.status(500).send(renderApiErr(req, res, 500, err))
    }
    console.log('手动添加管理员成功')
